[package]
name = "rust-musl"
version = "0.1.0"
authors = ["Ghost-str <someemail@example.somedomain>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
simple_logger = "1.11.0"
log = "0.4.14"